---
title: "My Projects"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

<br>

## Research Projects

<u>Design a SQL Relational Database for Wrong-Patient Errors</u>, *Center of Patient Safety Research*, 10/2022-now

<u>Establishing a Docker Image for Automated Compound Heterozygous (CH) Identification</u>, *Prof. Ali Gharavi’s lab*, 03/2022-08/2022

* Project Page: [DSI-comhet](https://github.com/YiruGONG/DSI-comhet)

<u>[Undergraduate thesis: Investigating the role of ADAR-mediated RNA-editing in Cardiomyopathy](./projects/RNAediting_Dissertation.pdf)</u>, *Prof. Roger Foo's Lab*, 01/2021-05/2021

* Project Page: [RNA-editing-from-RNAseq](https://github.com/YiruGONG/RNA-editing-from-RNAseq)

<u>Estimate the contribution of Gene-Environment Interactions in DNA methylation in cancer</u>, *Prof. Hangjin Jiang’s lab*, 09/2020-12/2020

* Project Page: [GxE-bayesian-estimation](https://github.com/YiruGONG/GxE-bayesian-estimation)

<u>[Explore the genetic and epigenetic regulation of promoter birth and death in human brain evolution](./projects/Report_YoungLab_yiru.pdf)</u>, *Prof. Robert Young’s lab*, 07/2020-08/2020

* Project Page: [brain_promoter_evolution](https://github.com/YiruGONG/brain_promoter_evolution)

<u>Develop the method in detecting differential expression of microRNA from isoform data in cancer</u>, *Prof. Hangjin Jiang’s lab*, 03/2020-06/2020

<u>Build computational reinforcement model for Morris Water Maze</u>, *Prof. Gedi Luksys's lab*, 01/2020-02/2020 (model unpublished yet)

<u>Analyze brain fMRI image between smoker and non-smoker by building statistical models</u>, *Prof. Hangjin Jiang’s lab*, 09/2019-12/2019

<br>

## Competitions

Humana-Mays Healthcare Analytics Case Competition: <u> [Analysis of Housing Insecurity](https://mays.tamu.edu/humana-tamu-analytics/)</u>, 08/2022-10/2022

* Project Page: [Humana-Competition](https://github.com/YiruGONG/Humana-competition)
* Business Report: [Analysis of Housing Insecurity](https://github.com/YiruGONG/Humana-competition/blob/main/2022CaseCompetition_Yiru_Gong_20221016.pdf)

CodaLab Competition: <u> [Covid-19 Infection Percentage Estimation](https://competitions.codalab.org/competitions/35575#learn_the_details)</u>, 01/2022-03/2022

* Project Page: [DL-Competition](https://github.com/BuddGao/DL-Competition)

<br>

## Course Projects

<br>

### Engineering and Databases

<u>[Building a Full Stack Website Application for Badminton Appointment System](https://youtu.be/KFq0ex0oiKk)</u>, *COMS 6156 - Cloud Computing*, 09/2022-12/2022

* Project Page: [6156-CUMC-Badminton-Service](https://github.com/YiruGONG/6156-CUMC-Badminton-Service)

<u>[Integrated Covid-19 Services Database and Website Interface](http://34.138.84.215:8111/)</u>, *COMS 4111 W Introduction To Databases*, 01/2022-05/2022

* Project Page: [COVID-19-Services-Cloud-Platform](https://github.com/Dantongtong/COVID-19-Services-Cloud-Platform)
* Please email [me](mailto:yg2832@cumc.columbia.edu) for live demo on GCP Server

<br>

### Machine Learning and Modeling

<u>[Effects of Critic/User Review Language on Movie Perception](https://drive.google.com/file/d/1PH5thgSIiz0qjFHcFbBxBPsBHdyN0vYK/view?usp=sharing)</u>, *QMSS 5067 GR - Natural Language Processing S*, 09/2022-12/2022

* Project Page: [QMSSGR5067_Group9](https://github.com/kk0918/QMSSGR5067_Group9)

<u>[Applying Masked Token Transformer (MaskGIT) in Long Audio Generation](https://youtu.be/KFq0ex0oiKk)</u>, *COMS 4995 W - Deep Learning*, 01/2022-05/2022

* Project Page: [W4995DL-Final](https://github.com/HawkDukez/W4995DL-Final)

<u>[Predicting Covid-19 Vaccination Status from Social-economic Variables](https://github.com/YiruGONG/DSII-covid-vacc-pred/blob/main/final_report.pdf)</u>, *BIST 8106 P - Data Science II*, 01/2022-05/2022

* Project Page: [DSII-covid-vacc-pred](https://github.com/YiruGONG/DSII-covid-vacc-pred)

<br>

### Data Visualization And Analytic Reports

<u>[Website of Global Happiness Score](https://yirugong.github.io/world_happiness_report.github.io/index.html)</u>, *P8105 Data Science*, 09/2021-12/2021

* Project Page: [
world_happiness_report.github.io](https://github.com/YiruGONG/world_happiness_report.github.io)

<br>

### Statistical Analysis

<u>[Structural Learning of rs-fMRI data in Heavy
Smokers](https://github.com/YiruGONG/P8124-Graphical-Models/blob/main/Graphical_Final_Project.pdf)</u>, *BIST 8124 P - Graphical Models Complex*, 09/2022-12/2022

* Project Page: [P8124-Graphical-Models](https://github.com/YiruGONG/P8124-Graphical-Models)

<u>[US Crime Rate Report](./projects/CR_Report.pdf)</u>, *P8130 Biostatistical Methods*, 09/2021-12/2021

* Project Page: [US_Crime_rate_MLR](https://github.com/YiruGONG/US_Crime_rate_MLR)

<br>

## Others

<u>Clinical AI & UM Automation</u>, *Anthem Health Data Analytics Intern*, 06/2022-08/2022

<u>Establishment of a Database to Track Differences in Medication Treatment Response by Ethnicity</u>, *GSK Digital Analyst Internship*, 03/2021-07/2021

<u>Natural Language Processing (NLP)-based Medical Knowledge Graph Establishment and Embedding</u>, *GSK Digital Analyst Internship*, 03/2021-07/2021